# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mariadb:10.4
    container_name: mymariadb
    restart: always
    ports: 
      - 3306:3306
    networks: 
      - my-shared-network
    environment:
      - MARIADB_ROOT_PASSWORD=geheim
    volumes:
      - c:/data/mysql:/var/lib/mysql
  schweine-service:
    image: dozent/schweine-service:latest
    container_name: schweine-service
    restart: always
    networks: 
      - my-shared-network
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - spring_datasource_url=jdbc:mariadb://mymariadb:3306/sokadb
      - spring_datasource_password=geheim
    volumes:
      - c:/data:/data
networks:
  my-shared-network: {}